version: "3.5"

services:
  asrserver_test:
    image: docker.io/freeyeti/dev-in-docker:python3.10-poetry1.4.0-gdal-dev
    env_file: ../.env
    environment:
      - IN_DEV_CONTAINER=yes
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ../:/code
      - pypoetrycache:/root/.cache/pypoetry

volumes:
  pypoetrycache:
