name: release

# on:
#   push:
#     branches:
#       - main
#       - master

on:
  release:
    types: [published]

env:
  # Define image names
  MODEL_IMAGE: ${{ secrets.MODEL_IMAGE }}
  REGISTRY: ghcr.io


jobs:
  config:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
        
      - name: Check output
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.ref_name }} > version.txt
          
      - name: Upload version file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-deployment
          path: version.txt

  ## Generate deployment files.
  generate-artifacts:
    needs: config

    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          
      - name: Check image version
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          echo $IMAGE_TAG
      - name: Generate deployment files
        env:
          IMAGE_TAG: ${{ github.ref_name }}
          WWW_DATA_PATH: ${{ secrets.WWW_DATA_PATH }}
          PULL_SECRET: ${{ secrets.PULL_SECRET }}
        run: |
          sed -i "s@MODEL_IMAGE@$__IMAGE__@g" k8s/deployment.model1.yaml
          sed -i "s@MODEL_IMAGE@$__IMAGE__@g" k8s/deployment.model2.yaml
          sed -i "s@${{ secrets.NODE_1_NAME }}@$__NODE_NAME__@g" k8s/deployment.model1.yaml
          sed -i "s@${{ secrets.NODE_2_NAME }}@$__NODE_NAME__@g" k8s/deployment.model2.yaml
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-deployment
          path: |
            k8s/deployment.model1.yaml
            k8s/deployment.model2.yaml

  deploy:
    needs: generate-artifacts

    runs-on: [ubuntu-latest]

    steps:
      - name: download deployment files
        uses: actions/download-artifact@v3
        env:
          IMAGE_TAG: ${{ github.ref_name }}
        with:
          name: ${{ github.event.repository.name }}-deployment
          path: ${{ github.ref_name }}
      
      - name: scp to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: ${{ github.ref_name }}
          target: ${{ secrets.DEPLOYMENTS_PATH }}
          
      - name : ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            kubectl apply -f ${{secrets.DEPLOYMENTS_PATH}}/${{ github.ref_name }}/deployment.model1.yaml
            kubectl apply -f ${{secrets.DEPLOYMENTS_PATH}}/${{ github.ref_name }}/deployment.model2.yaml
            kubectl apply -f ${{secrets.DEPLOYMENTS_PATH}}/${{ github.ref_name }}/service.model1.yaml
            kubectl apply -f ${{secrets.DEPLOYMENTS_PATH}}/${{ github.ref_name }}/service.model2.yaml
